name: Mirror to Org Repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Git author
        run: |
          git config --global user.name "Asiful Haque"
          git config --global user.email "asiful35-2961@diu.edu.bd"

      - name: Push to org repo using PAT
        env:
          PAT: ${{ secrets.MIRROR_TOKEN }}
        run: |
          git remote add mirror https://x-access-token:${PAT}@github.com/TaskPro-monitoring/desktop-monitoring-main-webapp.git
          git push mirror main --force
