name: Mirror to Org Repo

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # important to get full history

      - name: Push to org repo
        env:
          ORG_REPO: https://github.com/TaskPro-monitoring/desktop-monitoring-main-webapp.git
          TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          git remote add org https://x-access-token:${TOKEN}@github.com/TaskPro-monitoring/desktop-monitoring-main-webapp.git
          git push org main --force
