name: Mirror to Org Repo

on:
  push:
    branches:
      - main   # or your default branch

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to org repo
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git remote add mirror https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/TaskPro-monitoring/desktop-monitoring-main-webapp.git
          git push mirror main --force
