name: Sync to Org Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout personal repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git identity
        run: |
          git config --global user.name "Asiful Haque"
          git config --global user.email "your-email@example.com"

      - name: Push to org repo
        env:
          ORG_TOKEN: ${{ secrets.ORG_REPO_TOKEN }}
        run: |
          git remote add org "https://x-access-token:${ORG_TOKEN}@github.com/TaskPro-monitoring/desktop-monitoring-main-webapp.git"
          git push org main --force
